### ISSUE TITLE
Docker sql error

### ISSUE THREAD

**Issue by atidot3** [seven1240/xui#20]
After installing a new Debian 9 with docker version:
Docker version 18.03.0-ce, build 0520e24
docker-compose version 1.20.1, build 5d8c71b

running through the make:

make setup - [x]
make -[x ]
make sqlite-init - [ ]
running a lot of error:
Error: near line 1485: CHECK constraint failed: params
Error: near line 1486: CHECK constraint failed: params
Error: near line 1487: CHECK constraint failed: params
Error: near line 1488: CHECK constraint failed: params
Error: near line 1489: CHECK constraint failed: params
Error: near line 1490: CHECK constraint failed: params
Error: near line 1540: near "(": syntax error
Error: near line 1544: near "'||state as name
      FROM npa_nxx_company_ocn
      WHERE npa = ${caller_id_number:1:3} AND nxx = ${caller_id_number:4:3}
      LIMIT 1'": syntax error

Correct statement for syntax error is:

INSERT INTO params (realm, k, v) VALUES('cidlookup', 'sql', 'SELECT name||'' (''||type||'')'' AS name^M
      FROM phonebook p JOIN numbers n ON p.id = n.phonebook_id^M
      WHERE n.number=''${caller_id_number}''^M
      LIMIT 1');^M
INSERT INTO params (realm, k, v) VALUES('cidlookup', 'citystate-sql', 'SELECT ratecenter||'' ''||state as name^M
      FROM npa_nxx_company_ocn^M
      WHERE npa = ${caller_id_number:1:3} AND nxx = ${caller_id_number:4:3}^M
      LIMIT 1');^M

But still need a fix for CHECK constraint failed: params

**Comment by rocklau** [comment]
You could try to git pull again. We fixed this SQL issue.  987a268f80110a7d6e2065731f9e77867b23f7e2

I just tested ok with [docker wiki document ](https://github.com/seven1240/xui/commits/master) again.   

 

### xswitch-xui-dev

poll and start-up docker container:

```
make docker-dev-init
make docker-dev-start
```

init dev env (only need the first time)

```
# go inside docker container
make docker-dev-bash


make setup       #init dev env
make             #build js files
make sqlite-init #init db
exit # exit docker
```

restart container

```
make docker-dev-stop
make docker-dev-start
```

**Comment by atidot3** [comment]
Sql is installing and docket working thanks for the fix !
