### ISSUE TITLE
XUI - Ssql error.

### ISSUE THREAD

**Issue by atidot3** [seven1240/xui#22]
Hi there, according to your email i post my error here.

2018-03-30 15:11:33.489150 [ERR] mod_lua.cpp:103 /usr/local/freeswitch/scripts/blocks-2.lua:4: attempt to index global 'row' (a nil value)
stack traceback:
/usr/local/freeswitch/scripts/blocks-2.lua:4: in function </usr/local/freeswitch/scripts/blocks-2.lua:2>
[C]: in function 'query'
/usr/local/freeswitch/scripts/blocks-2.lua:17: in main chunk

![capture](https://user-images.githubusercontent.com/3525729/38541603-dfc30c30-3c9f-11e8-800e-06a6ca20c77e.png)

Generated LUA:

-- Describe this function...
function sql_callback()
  session:consoleLog("warning", 'CallBack !!!!!!' .. "\n")
  session:consoleLog("warning", (row.Number) .. "\n")
end

tts_engine = "tts_commandline"
tts_voice = "Ting-Ting"
session:set_tts_params(tts_engine, tts_voice)
session:setVariable("tts_engine", tts_engine)
session:setVariable("tts_voice", tts_voice)
session:answer()
dbh = freeswitch.Dbh("odbc://freeswitch:sa:password")
query = 'SELECT TOP 10 * FROM Numbers'
dbh:query(query, sql_callback)

**Comment by rocklau** [comment]
Please create a input parameter "row" for function sql_callback 

![image](https://user-images.githubusercontent.com/221825/38616721-97800684-3dc7-11e8-9c6c-13675708e70e.png)

**Comment by atidot3** [comment]
Seem better yea... Sorry for my misunderstanding, i throught Row was a global as C or C++.
I can now make SSQL query, thanks for help !.

**Comment by rocklau** [comment]
You are welcome. ^^
